Repository rovergulf/ngx-slice-kit, pull requests merged in 2021-03, with the labels that each got.

#46 Bug/nav tabs active state issue
  libs/ngx-slice-kit/src/lib/navigation/nav-tabs/nav-tabs.component.html
  libs/ngx-slice-kit/src/lib/navigation/nav-tabs/nav-tabs.component.scss
  libs/ngx-slice-kit/src/lib/navigation/nav-tabs/nav-tabs.component.ts
  libs/ngx-slice-kit/src/lib/navigation/nav-tabs/tab-link.directive.spec.ts
  src/app/docs/navigation/demo-navtabs/demo-navtabs.component.ts
  src/app/docs/navigation/demos/page-one/page-one.component.html
  src/app/docs/navigation/navigation-routing.module.ts
Labels: bug

#43 test/nav-tab;
  libs/ngx-slice-kit/src/lib/navigation/nav-tabs/tab-link.directive.spec.ts
Labels: testing

#50 Ng update
  CHANGELOG.md
  libs/ngx-slice-kit/package.json
  libs/ngx-slice-kit/src/lib/buttons/icon/icon.glyphs.ts
  package-lock.json
  package.json
  src/app/guides/home/home.component.html
Labels: enhancement

#51 Test/nav-tabs: new beginning
  libs/ngx-slice-kit/src/lib/navigation/nav-tabs/nav-tabs.component.html
  libs/ngx-slice-kit/src/lib/navigation/nav-tabs/nav-tabs.component.spec.ts
  libs/ngx-slice-kit/src/lib/navigation/nav-tabs/nav-tabs.component.ts
  libs/ngx-slice-kit/src/lib/navigation/nav-tabs/tab-link.directive.spec.ts
  libs/ngx-slice-kit/src/lib/navigation/nav-tabs/tab-link.directive.ts
  src/app/docs/navigation/demo-navtabs/demo-navtabs.component.html
  src/app/docs/navigation/demo-navtabs/demo-navtabs.component.ts
  src/index.html
Labels: testing

#54 Test/tabs
  libs/ngx-slice-kit/src/lib/navigation/tabs/tab/tab.component.spec.ts
  libs/ngx-slice-kit/src/lib/navigation/tabs/tab/tab.component.ts
  libs/ngx-slice-kit/src/lib/navigation/tabs/tabs.component.spec.ts
Labels: testing

#59 tests/popup
  libs/ngx-slice-kit/src/lib/modals/alert/alert.component.spec.ts
  libs/ngx-slice-kit/src/lib/modals/modals.module.ts
  libs/ngx-slice-kit/src/lib/modals/popup/popup.component.spec.ts
  libs/ngx-slice-kit/src/lib/modals/popup/popup.component.ts
  libs/ngx-slice-kit/src/lib/modals/popup/popup.directive.spec.ts
  libs/ngx-slice-kit/src/lib/modals/popup/popup.directive.ts
  libs/ngx-slice-kit/src/lib/modals/popup/popup.service.spec.ts
  libs/ngx-slice-kit/src/public-api.ts
Labels: testing

#60 tests/dialog
  libs/ngx-slice-kit/src/lib/buttons/button/button.component.spec.ts
  libs/ngx-slice-kit/src/lib/dropdowns/autocomplete/autocomplete.component.spec.ts
  libs/ngx-slice-kit/src/lib/dropdowns/dropdown.component.spec.ts
  libs/ngx-slice-kit/src/lib/dropdowns/select/select.component.spec.ts
  libs/ngx-slice-kit/src/lib/layout/carousel/carousel.component.spec.ts
  libs/ngx-slice-kit/src/lib/layout/pagination/pagination.component.spec.ts
  libs/ngx-slice-kit/src/lib/modals/alert/alert.component.spec.ts
  libs/ngx-slice-kit/src/lib/modals/alert/alerts.component.spec.ts
  libs/ngx-slice-kit/src/lib/modals/dialog/dialog.component.spec.ts
  libs/ngx-slice-kit/src/lib/modals/dialog/dialog.service.spec.ts
  libs/ngx-slice-kit/src/lib/modals/popup/popup.component.spec.ts
  libs/ngx-slice-kit/src/lib/modals/popup/popup.service.spec.ts
  libs/ngx-slice-kit/src/lib/navigation/nav-menu/nav-menu-group/nav-menu-group.component.spec.ts
  libs/ngx-slice-kit/src/lib/navigation/nav-tabs/nav-tabs.component.spec.ts
  libs/ngx-slice-kit/src/lib/navigation/tabs/tabs.component.spec.ts
Labels: testing

#61 test/scroll-directive
  libs/ngx-slice-kit/src/lib/core/directives/navigation-scroll.directive.spec.ts
  libs/ngx-slice-kit/src/lib/core/directives/navigation-scroll.directive.ts
  libs/ngx-slice-kit/tslint.json
Labels: testing

#62 test/tooltip
  libs/ngx-slice-kit/src/lib/core/styles/core.scss
  libs/ngx-slice-kit/src/lib/modals/tooltip/tooltip.component.html
  libs/ngx-slice-kit/src/lib/modals/tooltip/tooltip.component.scss
  libs/ngx-slice-kit/src/lib/modals/tooltip/tooltip.component.spec.ts
  libs/ngx-slice-kit/src/lib/modals/tooltip/tooltip.component.ts
  libs/ngx-slice-kit/src/lib/modals/tooltip/tooltip.directive.scss
  libs/ngx-slice-kit/src/lib/modals/tooltip/tooltip.directive.spec.ts
  libs/ngx-slice-kit/src/lib/modals/tooltip/tooltip.directive.ts
  libs/ngx-slice-kit/src/test.ts
  src/app/docs/modals/demo-tooltip/demo-tooltip.component.html
Labels: testing

#71 test/dots;
  libs/ngx-slice-kit/src/lib/layout/dots/dots.component.spec.ts
  libs/ngx-slice-kit/src/lib/layout/dots/dots.component.ts
  libs/ngx-slice-kit/src/test.ts
Labels: testing

#72 test/pagination
  libs/ngx-slice-kit/src/lib/layout/pagination/pagination.component.html
  libs/ngx-slice-kit/src/lib/layout/pagination/pagination.component.spec.ts
  libs/ngx-slice-kit/src/lib/layout/pagination/pagination.component.ts
  libs/ngx-slice-kit/src/test.ts
  src/app/docs/layout/demo-pagination/demo-pagination.component.ts
Labels: testing

#77 Test/progress
  libs/ngx-slice-kit/src/lib/layout/progress/progress.component.spec.ts
  libs/ngx-slice-kit/src/lib/layout/progress/progress.component.ts
  src/app/docs/layout/demo-progress/demo-progress.component.ts
Labels: testing

#78 required-input-attr
  libs/ngx-slice-kit/src/lib/dropdowns/autocomplete/autocomplete.component.ts
  libs/ngx-slice-kit/src/lib/dropdowns/select/select.component.ts
  libs/ngx-slice-kit/src/lib/inputs/input/input.component.ts
  libs/ngx-slice-kit/src/lib/inputs/textarea/textarea.component.html
  libs/ngx-slice-kit/src/lib/inputs/textarea/textarea.component.ts
  src/app/docs/inputs/demo-inputs/demo-inputs.component.html
Labels: invalid

#79 Checkbox unexpected margin
  libs/ngx-slice-kit/src/lib/inputs/checkbox/checkbox.component.scss
  libs/ngx-slice-kit/src/lib/inputs/radio/radio.component.html
  libs/ngx-slice-kit/src/lib/inputs/radio/radio.component.scss
Labels: bug

#81 Fix colors usage
  CHANGELOG.md
  libs/ngx-slice-kit/src/lib/buttons/button-group/button-group.component.html
  libs/ngx-slice-kit/src/lib/buttons/button-group/button-group.component.scss
  libs/ngx-slice-kit/src/lib/buttons/button-group/button-group.component.ts
  libs/ngx-slice-kit/src/lib/buttons/button/button.component.scss
  libs/ngx-slice-kit/src/lib/buttons/icon/icon.component.ts
  libs/ngx-slice-kit/src/lib/core/styles/core.scss
  libs/ngx-slice-kit/src/lib/core/theme/lib/theme-dark.ts
  libs/ngx-slice-kit/src/lib/core/theme/lib/theme-light.ts
  libs/ngx-slice-kit/src/lib/core/theme/theme.directive.ts
  libs/ngx-slice-kit/src/lib/core/theme/theme.model.ts
  libs/ngx-slice-kit/src/lib/dropdowns/autocomplete/autocomplete.component.html
  libs/ngx-slice-kit/src/lib/dropdowns/dropdown.component.html
  libs/ngx-slice-kit/src/lib/layout/layout.module.ts
  libs/ngx-slice-kit/src/lib/layout/pagination/pagination.component.html
  libs/ngx-slice-kit/src/lib/layout/pagination/pagination.component.scss
  libs/ngx-slice-kit/src/lib/layout/pagination/pagination.module.ts
  libs/ngx-slice-kit/src/lib/navigation/nav-menu/nav-menu-group/nav-menu-group.component.scss
  libs/ngx-slice-kit/src/lib/navigation/nav-menu/nav-menu-item/nav-menu-item.component.scss
  libs/ngx-slice-kit/src/lib/navigation/nav-tabs/nav-tabs.module.ts
  libs/ngx-slice-kit/src/public-api.ts
  src/app/docs/buttons/demo-buttons/demo-buttons.component.html
  src/app/guides/colors/colors.component.html
  src/app/guides/colors/colors.component.scss
  src/app/guides/get-started/get-started.component.ts
  src/app/guides/glyphs/glyphs.component.ts
  src/app/guides/guides.component.scss
  src/app/guides/guides.component.ts
  src/app/guides/guides.module.scss
  src/app/guides/home/home.component.html
  src/app/guides/home/home.component.scss
  src/app/guides/i18n/i18n.component.ts
  src/app/guides/images-grid/images-grid.component.ts
  src/app/shared/layout/header/header.component.scss
  src/styles.scss
Labels: blocks-next-version, enhancement

#87 tests-fixes
  libs/ngx-slice-kit/src/lib/buttons/button-group/button-group.component.spec.ts
  libs/ngx-slice-kit/src/lib/buttons/button-group/button-group.component.ts
  libs/ngx-slice-kit/src/lib/buttons/icon/icon.component.spec.ts
  libs/ngx-slice-kit/src/lib/dropdowns/autocomplete/autocomplete.component.spec.ts
  libs/ngx-slice-kit/src/lib/dropdowns/select/select.component.spec.ts
  libs/ngx-slice-kit/src/lib/inputs/input/input.component.scss
  libs/ngx-slice-kit/src/lib/inputs/input/input.component.spec.ts
  libs/ngx-slice-kit/src/lib/inputs/input/input.component.ts
  libs/ngx-slice-kit/src/lib/inputs/textarea/textarea.component.scss
  libs/ngx-slice-kit/src/lib/inputs/textarea/textarea.component.spec.ts
  libs/ngx-slice-kit/src/lib/inputs/toggle/toggle.component.scss
  libs/ngx-slice-kit/src/lib/inputs/toggle/toggle.component.spec.ts
  libs/ngx-slice-kit/src/test.ts
Labels: bug

#96 Color palette fix
  .gitignore
  libs/ngx-slice-kit/src/lib/inputs/input/input.component.html
  libs/ngx-slice-kit/src/lib/inputs/input/input.component.scss
  package-lock.json
  package.json
  src/app/docs/inputs/demo-inputs/demo-inputs.component.html
  src/app/docs/inputs/demo-inputs/demo-inputs.component.ts
Labels: bug

#97 do not use alpha colors
  CHANGELOG.md
  libs/ngx-slice-kit/CHANGELOG-v1.md
  libs/ngx-slice-kit/src/lib/core/styles/core.scss
  libs/ngx-slice-kit/src/lib/core/styles/variables.scss
  libs/ngx-slice-kit/src/lib/core/theme/lib/dark-theme.json
  libs/ngx-slice-kit/src/lib/core/theme/lib/light-theme.json
  libs/ngx-slice-kit/src/lib/core/theme/lib/theme-dark.ts
  libs/ngx-slice-kit/src/lib/core/theme/theme.directive.ts
  libs/ngx-slice-kit/src/lib/core/theme/theme.model.ts
  libs/ngx-slice-kit/src/lib/inputs/textarea/textarea.component.scss
Labels: enhancement

#90 Test/slider
  libs/ngx-slice-kit/src/lib/buttons/icon/icon.component.spec.ts
  libs/ngx-slice-kit/src/lib/core/layout-control/layout-control.service.spec.ts
  libs/ngx-slice-kit/src/lib/core/layout-control/layout-control.service.ts
  libs/ngx-slice-kit/src/lib/layout/pagination/pagination.component.html
  libs/ngx-slice-kit/src/lib/layout/pagination/pagination.component.scss
  libs/ngx-slice-kit/src/lib/layout/pagination/pagination.component.spec.ts
  libs/ngx-slice-kit/src/lib/layout/slider/slider.component.html
  libs/ngx-slice-kit/src/lib/layout/slider/slider.component.spec.ts
  libs/ngx-slice-kit/src/lib/layout/slider/slider.component.ts
Labels: testing

#116 do_not_use_site_values_for_kit_tests_while_drinking _your _juice_in_the_hood
  .github/workflows/main.yml
  libs/ngx-slice-kit/src/lib/dropdowns/autocomplete/autocomplete.component.spec.ts
  libs/ngx-slice-kit/src/lib/dropdowns/context/dropdown-menu-trigger.directive.spec.ts
  libs/ngx-slice-kit/src/lib/dropdowns/dropdown.component.spec.ts
  libs/ngx-slice-kit/src/lib/dropdowns/select/select.component.spec.ts
Labels: bug

#118 Test/layout control
  CHANGELOG.md
  libs/ngx-slice-kit/src/lib/core/layout-control/layout-control.service.spec.ts
  libs/ngx-slice-kit/src/lib/core/layout-control/layout-control.service.ts
  libs/ngx-slice-kit/src/lib/inputs/input/input.component.spec.ts
  libs/ngx-slice-kit/src/test.ts
Labels: testing

#119 loading tests
  CHANGELOG.md
  libs/ngx-slice-kit/src/lib/layout/loading/loading.component.spec.ts
  libs/ngx-slice-kit/src/lib/layout/loading/loading.directive.spec.ts
Labels: testing

#120 test/theme-service
  CHANGELOG.md
  libs/ngx-slice-kit/src/lib/core/theme/theme.model.ts
  libs/ngx-slice-kit/src/lib/core/theme/theme.service.spec.ts
  libs/ngx-slice-kit/src/lib/core/theme/theme.service.ts
Labels: testing

#121 test/theme-directive
  libs/ngx-slice-kit/src/lib/core/theme/theme.directive.spec.ts
  libs/ngx-slice-kit/src/lib/core/theme/theme.service.ts
Labels: testing

#122 Test/carousel
  CHANGELOG.md
  libs/ngx-slice-kit/karma.conf.js
  libs/ngx-slice-kit/src/lib/layout/carousel/carousel.component.spec.ts
  libs/ngx-slice-kit/src/lib/layout/carousel/carousel.component.ts
  libs/ngx-slice-kit/src/lib/layout/carousel/slide/slide.component.spec.ts
  src/app/docs/layout/demo-carousel/demo-carousel.component.ts
Labels: testing

#124 Test/up branch coverage
  libs/ngx-slice-kit/karma.conf.js
  libs/ngx-slice-kit/src/lib/buttons/button-group/button-group.component.spec.ts
  libs/ngx-slice-kit/src/lib/buttons/button-group/button-group.component.ts
  libs/ngx-slice-kit/src/lib/buttons/button/button.component.spec.ts
Labels: testing
