Repository rovergulf/ngx-slice-kit, pull requests merged in 2021-04, with the labels that each got.

#125 palette fix
  CHANGELOG.md
  libs/ngx-slice-kit/src/lib/buttons/button-group/button-group.component.scss
  libs/ngx-slice-kit/src/lib/buttons/button-group/button-group.component.spec.ts
  libs/ngx-slice-kit/src/lib/buttons/button-group/button-group.component.ts
  libs/ngx-slice-kit/src/lib/buttons/icon/icon.component.spec.ts
  libs/ngx-slice-kit/src/lib/buttons/icon/icon.component.ts
  libs/ngx-slice-kit/src/lib/buttons/icon/icon.glyphs.ts
  libs/ngx-slice-kit/src/lib/core/styles/core.scss
  libs/ngx-slice-kit/src/lib/core/styles/variables.scss
  libs/ngx-slice-kit/src/lib/core/theme/theme.directive.ts
  libs/ngx-slice-kit/src/lib/core/theme/theme.model.ts
  libs/ngx-slice-kit/src/lib/dropdowns/autocomplete/autocomplete.component.scss
  libs/ngx-slice-kit/src/lib/dropdowns/context/dropdown-menu-trigger.directive.spec.ts
  libs/ngx-slice-kit/src/lib/dropdowns/dropdown.component.scss
  libs/ngx-slice-kit/src/lib/dropdowns/dropdowns.module.ts
  libs/ngx-slice-kit/src/lib/dropdowns/select/select.component.scss
  libs/ngx-slice-kit/src/lib/inputs/checkbox/checkbox.component.scss
  libs/ngx-slice-kit/src/lib/inputs/checkbox/checkbox.component.spec.ts
  libs/ngx-slice-kit/src/lib/inputs/input/input.component.scss
  libs/ngx-slice-kit/src/lib/inputs/radio/radio.component.scss
  libs/ngx-slice-kit/src/lib/inputs/radio/radio.component.spec.ts
  libs/ngx-slice-kit/src/lib/inputs/textarea/textarea.component.scss
  libs/ngx-slice-kit/src/lib/inputs/textarea/textarea.component.ts
  libs/ngx-slice-kit/src/lib/inputs/toggle/toggle.component.scss
  libs/ngx-slice-kit/src/lib/inputs/toggle/toggle.component.spec.ts
  libs/ngx-slice-kit/src/lib/layout/carousel/carousel.component.scss
  libs/ngx-slice-kit/src/lib/layout/carousel/carousel.component.spec.ts
  libs/ngx-slice-kit/src/lib/layout/carousel/carousel.component.ts
  libs/ngx-slice-kit/src/lib/layout/dots/dots.component.scss
  libs/ngx-slice-kit/src/lib/layout/pagination/pagination.component.html
  libs/ngx-slice-kit/src/lib/layout/pagination/pagination.component.scss
  libs/ngx-slice-kit/src/lib/layout/pagination/pagination.component.spec.ts
  libs/ngx-slice-kit/src/lib/layout/progress/progress.component.scss
  libs/ngx-slice-kit/src/lib/layout/slider/slider.component.scss
  libs/ngx-slice-kit/src/lib/layout/slider/slider.component.spec.ts
  libs/ngx-slice-kit/src/lib/modals/alert/alert.component.html
  libs/ngx-slice-kit/src/lib/modals/alert/alert.component.scss
  libs/ngx-slice-kit/src/lib/modals/alert/alerts.component.html
  libs/ngx-slice-kit/src/lib/modals/alert/alerts.component.scss
  libs/ngx-slice-kit/src/lib/modals/dialog/dialog.component.ts
  libs/ngx-slice-kit/src/lib/modals/dialog/dialog.service.spec.ts
  libs/ngx-slice-kit/src/lib/navigation/nav-menu/nav-menu-group/nav-menu-group.component.html
  libs/ngx-slice-kit/src/lib/navigation/nav-menu/nav-menu-group/nav-menu-group.component.scss
  libs/ngx-slice-kit/src/lib/navigation/nav-menu/nav-menu-group/nav-menu-group.component.ts
  libs/ngx-slice-kit/src/lib/navigation/nav-menu/nav-menu-item/nav-menu-item.component.scss
  libs/ngx-slice-kit/src/lib/navigation/nav-menu/nav-menu.module.ts
  libs/ngx-slice-kit/src/lib/navigation/nav-tabs/nav-tabs.component.html
  libs/ngx-slice-kit/src/lib/navigation/nav-tabs/nav-tabs.component.scss
  libs/ngx-slice-kit/src/lib/navigation/tabs/tabs.component.html
  libs/ngx-slice-kit/src/lib/navigation/tabs/tabs.component.scss
  src/app/docs/dropdown/demo-select/demo-select.component.ts
  src/app/docs/modals/demo-dialog/demo-dialog-preview/demo-dialog-preview.component.html
  src/app/docs/modals/demo-dialog/demo-dialog-preview/demo-dialog-preview.component.ts
  src/app/docs/modals/demo-dialog/demo-dialog-preview2/demo-dialog-preview2.component.ts
  src/app/shared/layout/header/header.component.scss
  src/app/shared/layout/sidenav/sidenav.component.html
  src/styles.scss
Labels: blocks-next-version

#141 disable ivy compiler
  .github/workflows/npm_package.yml
  angular.json
  libs/ngx-slice-kit/tsconfig.lib.json
Labels: cloud-admin

#143 Toggle doc
  .github/workflows/build_publish_gcr.yml
  .github/workflows/test_kit.yml
  CHANGELOG.md
  README.md
  angular.json
  libs/ngx-slice-kit/package.json
  libs/ngx-slice-kit/src/lib/cards/card/card.module.ts
  libs/ngx-slice-kit/src/lib/modals/dialog/dialog.component.ts
  package-lock.json
  package.json
  src/app/app.module.ts
  src/app/docs/demo.module.scss
  src/app/docs/docs.module.ts
  src/app/docs/inputs/demo-switches/demo-switches.component.html
  src/app/docs/inputs/demo-switches/demo-switches.component.scss
  src/app/docs/inputs/demo-switches/demo-switches.component.ts
  src/app/docs/inputs/demo-toggle/demo-toggle.component.html
  src/app/docs/inputs/demo-toggle/demo-toggle.component.scss
  src/app/docs/inputs/demo-toggle/demo-toggle.component.spec.ts
  src/app/docs/inputs/demo-toggle/demo-toggle.component.ts
  src/app/docs/inputs/inputs-routing.module.ts
  src/app/docs/inputs/inputs.module.ts
  src/app/shared/layout/sidenav/sidenav.component.html
  src/styles.scss
  src/typings.d.ts
Labels: documentation

#165 ngFor for nav tabs
  CHANGELOG.md
  libs/ngx-slice-kit/package.json
  libs/ngx-slice-kit/src/lib/inputs/toggle/toggle.component.scss
  libs/ngx-slice-kit/src/lib/navigation/tabs/tabs.component.ts
  src/app/shared/components/demo/demo.component.html
Labels: bug

#164 Support codecov reports
  .editorconfig
  .github/workflows/build_publish_gcr.yml
  .github/workflows/npm_package.yml
  .github/workflows/test_kit.yml
  CHANGELOG.md
  README.md
  angular.json
  libs/ngx-slice-kit/karma.conf.js
  libs/ngx-slice-kit/package.json
  libs/ngx-slice-kit/src/lib/layout/divider/divider.component.scss
  package-lock.json
  package.json
  src/app/app.component.spec.ts
  src/app/docs/buttons/demo-badges/demo-badges.component.ts
  src/app/docs/buttons/demo-ripple/demo-ripple.component.ts
  src/app/docs/documents.component.spec.ts
  src/app/docs/dropdown/demo-autocomplete/demo-autocomplete.component.ts
  src/app/docs/dropdown/demo-dropdown/demo-dropdown.component.ts
  src/app/docs/dropdown/demo-select/demo-select.component.ts
  src/app/docs/inputs/demo-radio/demo-radio.component.ts
  src/app/docs/inputs/demo-toggle/demo-toggle.component.ts
  src/app/docs/layout/demo-slides/demo-slides.component.ts
  src/app/guides/get-started/get-started.component.html
  src/app/guides/get-started/get-started.component.scss
  src/app/guides/get-started/get-started.component.ts
  src/app/guides/glyphs/glyphs.component.scss
  src/app/guides/glyphs/glyphs.component.ts
  src/app/guides/guides.module.ts
  src/app/guides/home/home.component.html
  src/app/guides/home/home.component.scss
  src/app/shared/components/demo/demo.component.html
  src/app/shared/components/demo/demo.component.scss
  src/app/shared/components/demo/demo.component.ts
  src/app/shared/model/demo-component.model.ts
  src/app/shared/shared.module.ts
  src/styles.scss
Labels: testing

#167 Gcr env fix
  .github/workflows/build_publish_gcr.yml
  src/app/guides/home/home.component.html
Labels: cloud-admin

#168 up test coverage
  CHANGELOG.md
  libs/ngx-slice-kit/src/lib/inputs/checkbox/checkbox.component.spec.ts
  libs/ngx-slice-kit/src/lib/inputs/input/input.component.spec.ts
  libs/ngx-slice-kit/src/lib/inputs/radio/radio.component.spec.ts
  libs/ngx-slice-kit/src/lib/inputs/textarea/textarea.component.spec.ts
  libs/ngx-slice-kit/src/lib/inputs/toggle/toggle.component.spec.ts
  libs/ngx-slice-kit/src/lib/layout/progress/progress.component.spec.ts
  libs/ngx-slice-kit/src/lib/layout/slider/slider.component.spec.ts
  libs/ngx-slice-kit/src/lib/modals/popup/popup.service.spec.ts
  src/app/guides/home/home.component.html
Labels: testing

#170 Adaptive demos
  CHANGELOG.md
  src/app/app.module.ts
  src/app/docs/inputs/demo-radio/demo-radio.component.ts
  src/app/docs/inputs/demo-textarea/demo-textarea.component.html
  src/app/docs/inputs/demo-textarea/demo-textarea.component.scss
  src/app/docs/inputs/demo-textarea/demo-textarea.component.ts
  src/app/docs/inputs/demo-toggle/demo-toggle.component.ts
  src/app/guides/get-started/get-started.component.html
  src/app/guides/get-started/get-started.component.scss
  src/app/guides/guides.module.ts
  src/app/shared/components/code-snippet/code-snippet.component.html
  src/app/shared/components/code-snippet/code-snippet.component.scss
  src/app/shared/components/code-snippet/code-snippet.component.ts
  src/app/shared/components/demo/demo.component.html
  src/app/shared/components/demo/demo.component.scss
  src/app/shared/components/demo/demo.component.ts
  src/app/shared/shared.module.ts
Labels: bug

#176 theming guide update
  CHANGELOG.md
  src/app/guides/get-started/get-started.component.ts
  src/app/guides/glyphs/glyphs.component.ts
  src/app/guides/guides-routing.module.ts
  src/app/guides/guides.component.html
  src/app/guides/guides.component.scss
  src/app/guides/guides.module.scss
  src/app/guides/guides.module.ts
  src/app/guides/images-grid/images-grid.component.ts
  src/app/guides/md-usage/md-usage.component.html
  src/app/guides/md-usage/md-usage.component.ts
  src/app/guides/schematics/schematics.component.html
  src/app/guides/schematics/schematics.component.scss
  src/app/guides/schematics/schematics.component.ts
  src/app/guides/theming/theming.component.html
  src/app/guides/theming/theming.component.scss
  src/app/guides/theming/theming.component.ts
  src/app/resources/about/about.component.html
  src/app/resources/about/about.component.spec.ts
  src/app/resources/resources-routing.module.ts
  src/app/resources/resources.component.spec.ts
  src/app/resources/resources.module.scss
  src/app/resources/resources.module.ts
  src/app/resources/roadmap/roadmap.component.html
  src/app/resources/roadmap/roadmap.component.scss
  src/app/resources/roadmap/roadmap.component.spec.ts
  src/app/resources/roadmap/roadmap.component.ts
  src/app/resources/slice-design/slice-design.component.html
  src/app/resources/slice-design/slice-design.component.scss
  src/app/resources/slice-design/slice-design.component.spec.ts
  src/app/resources/slice-design/slice-design.component.ts
  src/app/shared/components/api-def-table/api-def-table.component.html
  src/app/shared/components/api-def-table/api-def-table.component.scss
  src/app/shared/components/api-def-table/api-def-table.component.spec.ts
  src/app/shared/components/api-def-table/api-def-table.component.ts
  src/app/shared/components/demo/demo.component.html
  src/app/shared/components/theme-color/theme-color.component.html
  src/app/shared/components/theme-color/theme-color.component.scss
  src/app/shared/components/theme-color/theme-color.component.ts
  src/app/shared/layout/sidenav/sidenav.component.html
  src/app/shared/model/api-definition.model.ts
  src/app/shared/model/demo-page.model.ts
  src/app/shared/shared.module.ts
Labels: enhancement

#177 Pagination demo
  CHANGELOG.md
  src/app/docs/layout/demo-pagination/demo-pagination.component.html
  src/app/docs/layout/demo-pagination/demo-pagination.component.ts
  src/app/docs/layout/demo-progress/demo-progress.component.html
  src/app/docs/layout/demo-progress/demo-progress.component.ts
  src/app/docs/layout/demo-slides/demo-slides.component.html
  src/app/docs/layout/demo-slides/demo-slides.component.ts
  src/app/guides/guides.module.scss
Labels: documentation

#178 Sidenav demo
  CHANGELOG.md
  src/app/app.component.html
  src/app/docs/layout/demo-accordion/demo-accordion.component.ts
  src/app/docs/navigation/demo-sidenav/demo-sidenav.component.html
  src/app/docs/navigation/demo-sidenav/demo-sidenav.component.scss
  src/app/docs/navigation/demo-sidenav/demo-sidenav.component.ts
  src/app/shared/components/demo/demo.component.html
  src/app/shared/components/demo/demo.component.scss
  src/app/shared/model/demo-page.model.ts
Labels: documentation

#181 theming guide customizing
  CHANGELOG.md
  libs/ngx-slice-kit/package.json
  libs/ngx-slice-kit/src/lib/core/theme/theme.model.ts
  libs/ngx-slice-kit/src/lib/core/theme/theme.service.ts
  libs/ngx-slice-kit/src/public-api.ts
  package.json
  src/app/guides/get-started/get-started.component.ts
  src/app/guides/theming/theming.component.html
  src/app/guides/theming/theming.component.scss
  src/app/guides/theming/theming.component.ts
  src/app/shared/components/api-def-table/api-def-table.component.html
  src/app/shared/components/api-def-table/api-def-table.component.ts
  src/app/shared/components/demo/demo.component.html
  src/app/shared/components/demo/demo.component.ts
  src/app/shared/components/gen-theme/gen-theme.component.html
  src/app/shared/components/gen-theme/gen-theme.component.scss
  src/app/shared/components/gen-theme/gen-theme.component.ts
  src/app/shared/components/theme-color/theme-color.component.html
  src/app/shared/components/theme-color/theme-color.component.scss
  src/app/shared/components/theme-color/theme-color.component.ts
  src/app/shared/components/theme-settings/theme-settings.component.html
  src/app/shared/components/theme-settings/theme-settings.component.scss
  src/app/shared/components/theme-settings/theme-settings.component.ts
  src/app/shared/layout/sidenav/sidenav.component.html
  src/app/shared/layout/sidenav/sidenav.component.ts
  src/app/shared/model/api-argument.model.ts
  src/app/shared/model/api-definition.model.ts
  src/app/shared/model/demo-page.model.ts
  src/app/shared/services/layout.service.ts
  src/app/shared/shared.module.ts
Labels: documentation, enhancement

#185 Dropdowns demo
  CHANGELOG.md
  libs/ngx-slice-kit/package.json
  libs/ngx-slice-kit/src/lib/core/styles/core.scss
  libs/ngx-slice-kit/src/lib/dropdowns/autocomplete/autocomplete.component.scss
  libs/ngx-slice-kit/src/lib/dropdowns/autocomplete/autocomplete.component.spec.ts
  libs/ngx-slice-kit/src/lib/dropdowns/autocomplete/autocomplete.component.ts
  libs/ngx-slice-kit/src/lib/dropdowns/context/dropdown-menu-trigger.directive.ts
  package.json
  src/app/docs/buttons/demo-buttons/demo-buttons.component.ts
  src/app/docs/dropdown/demo-autocomplete/demo-autocomplete.component.html
  src/app/docs/dropdown/demo-autocomplete/demo-autocomplete.component.scss
  src/app/docs/dropdown/demo-autocomplete/demo-autocomplete.component.ts
  src/app/docs/dropdown/demo-dropdown/demo-dropdown.component.html
  src/app/docs/dropdown/demo-dropdown/demo-dropdown.component.scss
  src/app/docs/dropdown/demo-dropdown/demo-dropdown.component.ts
  src/app/docs/dropdown/demo-select/demo-select.component.html
  src/app/docs/dropdown/demo-select/demo-select.component.scss
  src/app/docs/dropdown/demo-select/demo-select.component.ts
  src/app/shared/values/dropdowns.values.ts
Labels: documentation

#192 add popup api doc
  ANGULAR.md
  CHANGELOG.md
  SECURITY.md
  src/app/docs/modals/demo-alerts/demo-alerts.component.ts
  src/app/docs/modals/demo-dialog/demo-dialog.component.ts
  src/app/docs/modals/demo-popup/demo-popup.component.ts
  src/app/shared/components/api-def-table/api-def-table.component.html
  src/app/shared/components/api-def-table/api-def-table.component.ts
  src/app/shared/components/demo/demo.component.html
  src/app/shared/model/api-group.model.ts
Labels: documentation
